Document updates
intel/trusted-certificate-issuer pull request #1
Opened 2022-02-02 08:49 UTC by poussa

- Improve links
- Fix incorrect info
- Improve language
- Clarify prerequisites

2022-02-02 09:10 UTC, ipuustin requested changes
One small nit, otherwise LGTM

2022-02-02 09:10 UTC, ipuustin commented on docs/integrate-key-server.md
> +By default, the Trusted Certificate Service (TCS) expects the CA private key and root certificate are provisioned by an external key management services like [Intel® KMRA](https://01.org/key-manageme
"an external key management services" -> "an external key management service"

2022-02-02 14:09 UTC, ipuustin commented
Thanks! Can you squash the commits? Let's merge then.

2022-02-02 14:57 UTC, avalluri commented on docs/integrate-key-server.md
> +By default, the Trusted Certificate Service (TCS) expects the CA private key and root certificate are provisioned by an external key management service like [Intel® KMRA](https://01.org/key-managemen
Currently, the default behavior is self-sign key and certificate, Quote attestation is only when `tcsissuer.spec.selfSign` set to `false`.

2022-02-03 07:39 UTC, poussa commented
@ipuustin, @avalluri: All review comments fixed and commits squashed.

2022-02-03 07:52 UTC, avalluri approved these changes
Looks good to me.

2022-02-03 07:54 UTC, ipuustin approved these changes

2022-02-03 07:55 UTC, merged