add codegen annotations in quoteattestation API
intel/trusted-certificate-issuer pull request #68
Opened 2022-11-08 06:43 UTC by giantcroc

Codegen tools like deepcopy-gen and client-gen are used to generate client API in sds server, 
and we also would like to reuse quoteattestation API of TCS issuer,
so there are some codegen annotations needed to add to quoteattestation API.

2022-11-08 06:44 UTC, giantcroc commented
@avalluri Hi, amar! could you help review this PR? Thanks!

2022-11-08 07:26 UTC, avalluri requested changes
> @avalluri Hi, amar! could you help review this PR? Thanks!

@giantcroc  Thanks for the PR. The change itself looks good to me. Except for one comment, We [recently](#64) moved the QutoeAttestation API to `v1alpha2`. Can you please consider changing that also?

2022-11-10 05:43 UTC, giantcroc commented
> > @avalluri Hi, amar! could you help review this PR? Thanks!
> 
> @giantcroc Thanks for the PR. The change itself looks good to me. Except for one comment, We [recently](#64) moved the QutoeAttestation API to `v1alpha2`. Can you please consider changing that also?

OK, I have added same comments in v1alpha2. Thanks!

2022-11-11 07:32 UTC, avalluri approved these changes
Looks good to me.

2022-11-11 13:12 UTC, merged